<?php

declare(strict_types=1);

/*
 * UserFrosting Account Sprinkle (http://www.userfrosting.com)
 *
 * @link      https://github.com/userfrosting/sprinkle-account
 * @copyright Copyright (c) 2013-2024 Alexander Weissman & Louis Charette
 * @license   https://github.com/userfrosting/sprinkle-account/blob/master/LICENSE.md (MIT License)
 */

namespace UserFrosting\Sprinkle\Account\Database\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\MorphTo;
use Illuminate\Database\Query\Builder as QueryBuilder;
use UserFrosting\Sprinkle\Account\Database\Factories\ActivityFactory;
use UserFrosting\Sprinkle\Account\Database\Models\Interfaces\ActivityInterface;
use UserFrosting\Sprinkle\Account\Database\Models\Interfaces\UserInterface;
use UserFrosting\Sprinkle\Core\Database\Models\Model;

/**
 * Activity Model.
 *
 * Represents an activity generated by a user at a specified point in time.
 * Provide a context and subject to the activity to link it to other models.
 * The context is the model that the activity belongs to, while the subject
 * is the model that the activity is targeting.
 *
 * For example, if a user comments on a post, the context would be the post,
 * and the subject would be the comment. This allows for a more flexible
 * representation of activities, as they can be linked to any model in the
 * application, and thus displayed in a more meaningful and specific way to the
 * users (eg. show activities related to a specific post, comment, or a
 * specific user).
 *
 * @mixin \Illuminate\Database\Eloquent\Builder
 */
class Activity extends Model implements ActivityInterface
{
    use HasFactory;

    /**
     * @var string The name of the table for the current model.
     */
    protected $table = 'activities';

    /**
     * @var array<int, string> The attributes that are mass assignable.
     */
    protected $fillable = [
        'ip_address',
        'user_id',
        'context_type',
        'context_id',
        'subject_type',
        'subject_id',
        'type',
        'metadata',
        'occurred_at',
        'description', // @deprecated 6.1 kept for backward compatibility
    ];

    /**
     * @var string[] The attributes that should be cast.
     */
    protected $casts = [
        'user_id'     => 'integer',
        'metadata'    => 'array',
        'occurred_at' => 'datetime',
    ];

    /**
     * @var bool Disable timestamps for this class.
     */
    public $timestamps = false;

    /**
     * Cast nullable description to empty string if null.
     *
     * @param string|null $value
     *
     * @return string
     */
    public function getDescriptionAttribute(?string $value): string
    {
        return $value ?? '';
    }

    /**
     * {@inheritDoc}
     */
    public function scopeJoinUser(Builder $query): Builder|QueryBuilder
    {
        return $query->select('activities.*')
            ->join('users', 'activities.user_id', '=', 'users.id');
    }

    /**
     * {@inheritDoc}
     */
    public function scopeForType(Builder $query, string $type): Builder|QueryBuilder
    {
        return $query->where('type', $type);
    }

    /**
     * {@inheritDoc}
     */
    public function user(): BelongsTo
    {
        /** @var string */
        $relation = static::$ci?->get(UserInterface::class);

        return $this->belongsTo($relation, 'user_id');
    }

    /**
     * Get the contextual model this activity belongs to.
     */
    public function context(): MorphTo
    {
        return $this->morphTo();
    }

    /**
     * Get the secondary model targeted by this activity.
     */
    public function subject(): MorphTo
    {
        return $this->morphTo();
    }

    /**
     * Create a new factory instance for the model.
     *
     * @return Factory<Activity>
     */
    protected static function newFactory(): Factory
    {
        return ActivityFactory::new();
    }
}
