name: PHPStan

on:
  push:
    branches: [6.0, 6.1]
    paths:
        - packages/framework/**
        - packages/skeleton/**
        - packages/sprinkle-account/**
        - packages/sprinkle-admin/**
        - packages/sprinkle-core/**
  pull_request:
    branches: [6.0, 6.1]
    paths:
        - packages/framework/**
        - packages/skeleton/**
        - packages/sprinkle-account/**
        - packages/sprinkle-admin/**
        - packages/sprinkle-core/**
  workflow_dispatch:

jobs:
  PHPStan:

    strategy:
      fail-fast: false
      matrix:
        php_versions: ['8.3', '8.4', '8.5']

    runs-on: ubuntu-latest
    name: PHPStan - ${{ matrix.php_versions }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup PHP,with composer and extensions
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_versions }}

    - name: Install Dependencies
      run: composer update --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Run PHPStan
      run: vendor/bin/phpstan analyse
